zoo:
  guide:
    diy:
      zoo-i18n-spring:
        order: 1020
        name: "zoo-diy-feature-i18n-by-spring"
        instruction: |-
          1.此组件提供国际化能力支持
        manual: |-
          引入此组件后，你还需要作以下步骤：
          1.在src/main/resources/i18n目录下创建对应语言的文件，格式为 'messages_{语言}_{国家或地区}.properties' 如：
            messages_en_US.properties：英文
            messages_zh_CN.properties：简体中文
            messages_zh_TW.properties：繁体中文
          2.返回响应前，对需要i18n处理的字段，调用I18nUtil.i18n(...)转换，如：
            String message = I18nUtil.i18n(messageKey)
        contacts:
          - name: "作者邮箱"
            value: "13548417409@163.com"

# 指定消息文件为 i18n/messages
spring:
  messages:
    encoding: UTF-8
    basename: i18n/messages